namespace: retail-app

image:
  registry: public.ecr.aws/aws-containers
  tag: "1.6.1"
  legacyTag: "0.7.0"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 4

database:
  secretName: catalog-db-credentials

ingress:
  host: store.saphigen.com
  certificateArn: ""

externalSecrets:
  secretStoreName: aws-secrets-store
  awsSecretKey: bedrock/catalog-db
