apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-db-secret
  namespace: retail-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: catalog-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: bedrock/catalog-db
        property: username
    - secretKey: password
      remoteRef:
        key: bedrock/catalog-db
        property: password
    - secretKey: endpoint
      remoteRef:
        key: bedrock/catalog-db
        property: endpoint
    - secretKey: dbname
      remoteRef:
        key: bedrock/catalog-db
        property: dbname
